// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Layout() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"es\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Web Example</title><!-- Fuente Inter desde Google Fonts --><link rel=\"preconnect\" href=\"https://fonts.googleapis.com\"><link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin><link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap\" rel=\"stylesheet\"><link href=\"https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap\" rel=\"stylesheet\"><script src=\"https://cdn.tailwindcss.com\"></script><script>\n\t\t\t\ttailwind.config = {\n\t\t\t\t\ttheme: {\n\t\t\t\t\t\textend: {\n\t\t\t\t\t\t\tfontFamily: {\n\t\t\t\t\t\t\t\t'sans': ['Nunito', 'Inter', 'ui-sans-serif', 'system-ui'],\n\t\t\t\t\t\t\t},\n\t\t\t\t\t\t\tcolors: {\n\t\t\t\t\t\t\t\t'groupie-primary': '#3a1c32',\n\t\t\t\t\t\t\t\t'groupie-secondary': '#18181b',\n\t\t\t\t\t\t\t\t'groupie-accent': '#a83250',\n\t\t\t\t\t\t\t\t'groupie-accent-light': '#a83250',\n\t\t\t\t\t\t\t\t'groupie-success': '#01b796',\n\t\t\t\t\t\t\t\t'groupie-warning': '#facc15',\n\t\t\t\t\t\t\t\t'groupie-danger': '#ef4444',\n\t\t\t\t\t\t\t\t'groupie-dark': '#3a1c32',\n\t\t\t\t\t\t\t\t'groupie-darker': '#18181b',\n\t\t\t\t\t\t\t\t'groupie-card': '#3a1c32',\n\t\t\t\t\t\t\t\t'groupie-card-hover': '#a83250',\n\t\t\t\t\t\t\t\t'groupie-text': '#f4f4f5',\n\t\t\t\t\t\t\t\t'groupie-text-muted': '#a1a1aa',\n\t\t\t\t\t\t\t\t'groupie-border': '#ffffff4d',\n\t\t\t\t\t\t\t\t'groupie-border-light': '#ffffff33'\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t</script><style>\n\t\t\t\tbody {\n\t\t\t\t\tbackground: url('/static/img/background.png') #3a1c32 !important;\n\t\t\t\t}\n\t\t\t</style></head><body class=\"min-h-screen text-groupie-text\"><div class=\"container mx-auto\"><h1>Hello, World!</h1></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
